apiVersion: v1
kind: Pod
metadata:
  name: mc1
spec:
  volumes:
  - name: html
    emptyDir: {}
  - name: unbound-conf
    configMap:
      name: monolith-dns-cache-conf
  containers:
  - name: 1st
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  - name: 2nd
    image: debian
    volumeMounts:
    - name: html
      mountPath: /html
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date >> /html/index.html;
          sleep 1;
        done
  - image: mvance/unbound
    imagePullPolicy: IfNotPresent
    name: dns-local-cache
    volumeMounts:
    - mountPath: /etc/unbound/unbound.conf
      name: unbound-conf
      readOnly: true
      subPath: unbound.conf
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 127.0.0.1
    options:
    - name: ndots
      value: "1"
    searches:
      - default.svc.cluster.local
