apiVersion: batch/v1
kind: CronJob
metadata:
  name: lego-cert-renewal-cronjob
spec:
  schedule: 1 7 * * 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: lego-renewal
            image: goacme/lego:latest
            env:
              - name: DUCKDNS_TOKEN
                valueFrom:
                  secretKeyRef:
                    key: token
                    name: dnssec
            args:
            - --accept-tos
            - --domains=smjagadish.duckdns.org
            - --email=smjj@abc.com
            - --path=/tmp/lego
            - --dns=duckdns
            - renew
            volumeMounts:
              - mountPath: /tmp/lego
                name: lego-certificate-claim-volume-reference
          restartPolicy: OnFailure
          volumes:
            - name: lego-certificate-claim-volume-reference
              persistentVolumeClaim:
                claimName: lego-certificate-claim
